//! GATE 2 (schema half): the Rust DDL generator must reproduce the *same*
//! Postgres schema the TS node produces.
//!
//! The fixture `fixtures/schema.expected.json` is ground truth generated by
//! `scripts/gen-schema-fixture.cjs`, which runs the real TS path
//! (@subql/utils + Sequelize `sync()`) and introspects the result. This test
//! parses the same `schema.graphql`, generates DDL in Rust, applies it to an
//! ephemeral schema, introspects it, and asserts column-level equality.
//!
//! Skips if no Postgres is reachable (keeps CI green); regenerate the fixture
//! with the script when the schema or TS mapping changes.

use std::collections::BTreeMap;

use serde::Deserialize;
use subql_config::DbConfig;
use subql_store::{ddl, parse_entities, Database};

#[derive(Debug, Deserialize)]
struct Fixture {
    tables: BTreeMap<String, ExpectedTable>,
}

#[derive(Debug, Deserialize)]
struct ExpectedTable {
    columns: Vec<ExpectedColumn>,
}

#[derive(Debug, Deserialize, PartialEq, Eq)]
struct ExpectedColumn {
    name: String,
    data_type: String,
    is_nullable: bool,
}

async fn try_db() -> Option<Database> {
    let cfg = DbConfig::from_env();
    match Database::connect(&cfg) {
        Ok(db) => match db.ping().await {
            Ok(()) => Some(db),
            Err(e) => {
                eprintln!("[skip] postgres not reachable ({e})");
                None
            }
        },
        Err(e) => {
            eprintln!("[skip] pool build failed ({e})");
            None
        }
    }
}

fn unique_schema() -> String {
    use std::time::{SystemTime, UNIX_EPOCH};
    let nanos = SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .unwrap()
        .as_nanos();
    format!("subql_parity_{nanos}")
}

#[tokio::test]
async fn rust_ddl_matches_ts_ground_truth() {
    let Some(db) = try_db().await else { return };

    let sdl = include_str!("fixtures/schema.graphql");
    let expected: Fixture =
        serde_json::from_str(include_str!("fixtures/schema.expected.json")).expect("parse fixture");

    let models = parse_entities(sdl).expect("parse entities");
    let schema = unique_schema();
    db.ensure_schema(&schema).await.expect("create schema");

    let outcome = async {
        for stmt in ddl::create_tables(&models, &schema).expect("generate ddl") {
            db.batch_execute(&stmt).await.expect("apply ddl");
        }

        let info = db.introspect_schema(&schema).await.expect("introspect");

        // Compare table set.
        let got_tables: Vec<&String> = info.tables.keys().collect();
        let want_tables: Vec<&String> = expected.tables.keys().collect();
        assert_eq!(got_tables, want_tables, "table names differ");

        // Compare each table's columns (name, type, nullability).
        for (table, want) in &expected.tables {
            let got = info.tables.get(table).expect("table present");
            let got_cols: Vec<ExpectedColumn> = got
                .columns
                .iter()
                .map(|c| ExpectedColumn {
                    name: c.name.clone(),
                    data_type: c.data_type.clone(),
                    is_nullable: c.is_nullable,
                })
                .collect();
            let mut want_cols: Vec<&ExpectedColumn> = want.columns.iter().collect();
            want_cols.sort_by(|a, b| a.name.cmp(&b.name)); // introspect sorts by name
            let want_cols: Vec<ExpectedColumn> = want_cols
                .into_iter()
                .map(|c| ExpectedColumn {
                    name: c.name.clone(),
                    data_type: c.data_type.clone(),
                    is_nullable: c.is_nullable,
                })
                .collect();

            assert_eq!(got_cols, want_cols, "columns differ for table {table}");
        }
    }
    .await;

    db.drop_schema(&schema).await.expect("drop schema");
    outcome
}
